In [131]:
import polars as pl

In [132]:
path = '../data/raw/ai4i2020.csv'
df_raw = pl.read_csv(path)
print('Dataset loaded')
print(f'Rows: {df_raw.shape[0]}')
print(f'Columns: {df_raw.shape[1]}')

df_raw.sample(10)

Dataset loaded
Rows: 10000
Columns: 14

shape: (10, 14)
┌──────┬────────────┬──────┬─────────────────────┬───┬─────┬─────┬─────┬─────┐
│ UDI  ┆ Product ID ┆ Type ┆ Air temperature [K] ┆ … ┆ HDF ┆ PWF ┆ OSF ┆ RNF │
│ ---  ┆ ---        ┆ ---  ┆ ---                 ┆   ┆ --- ┆ --- ┆ --- ┆ --- │
│ i64  ┆ str        ┆ str  ┆ f64                 ┆   ┆ i64 ┆ i64 ┆ i64 ┆ i64 │
╞══════╪════════════╪══════╪═════════════════════╪═══╪═════╪═════╪═════╪═════╡
│ 1662 ┆ M16521     ┆ M    ┆ 298.2               ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ 6084 ┆ L53263     ┆ L    ┆ 300.9               ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ 2185 ┆ L49364     ┆ L    ┆ 299.8               ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ 9525 ┆ H38938     ┆ H    ┆ 299.0               ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ 7254 ┆ L54433     ┆ L    ┆ 300.3               ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ 711  ┆ M15570     ┆ M    ┆ 297.5               ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ 4783 ┆ L51962     ┆ L    ┆ 303.8               ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ 106  ┆ L47285     ┆ L    ┆ 298.8               ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ 6455 ┆ L53634     ┆ L    ┆ 300.7               ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ 3732 ┆ M18591     ┆ M    ┆ 302.2               ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
└──────┴────────────┴──────┴─────────────────────┴───┴─────┴─────┴─────┴─────┘

In [133]:
print('Columns:')
print(df_raw.columns)
print('\nData Quality')
df_raw.describe()

Columns:
['UDI', 'Product ID', 'Type', 'Air temperature [K]', 'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]', 'Machine failure', 'TWF', 'HDF', 'PWF', 'OSF', 'RNF']

Data Quality

shape: (9, 15)
┌────────────┬────────────┬────────────┬───────┬───┬──────────┬──────────┬──────────┬─────────┐
│ statistic  ┆ UDI        ┆ Product ID ┆ Type  ┆ … ┆ HDF      ┆ PWF      ┆ OSF      ┆ RNF     │
│ ---        ┆ ---        ┆ ---        ┆ ---   ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---     │
│ str        ┆ f64        ┆ str        ┆ str   ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64     │
╞════════════╪════════════╪════════════╪═══════╪═══╪══════════╪══════════╪══════════╪═════════╡
│ count      ┆ 10000.0    ┆ 10000      ┆ 10000 ┆ … ┆ 10000.0  ┆ 10000.0  ┆ 10000.0  ┆ 10000.0 │
│ null_count ┆ 0.0        ┆ 0          ┆ 0     ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0     │
│ mean       ┆ 5000.5     ┆ null       ┆ null  ┆ … ┆ 0.0115   ┆ 0.0095   ┆ 0.0098   ┆ 0.0019  │
│ std        ┆ 2886.89568 ┆ null       ┆ null  ┆ … ┆ 0.106625 ┆ 0.097009 ┆ 0.098514 ┆ 0.04355 │
│ min        ┆ 1.0        ┆ H29424     ┆ H     ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0     │
│ 25%        ┆ 2501.0     ┆ null       ┆ null  ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0     │
│ 50%        ┆ 5001.0     ┆ null       ┆ null  ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0     │
│ 75%        ┆ 7500.0     ┆ null       ┆ null  ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.0     │
│ max        ┆ 10000.0    ┆ M24859     ┆ M     ┆ … ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ 1.0     │
└────────────┴────────────┴────────────┴───────┴───┴──────────┴──────────┴──────────┴─────────┘

In [134]:
print(f'Double verification for null rows')
df_raw.null_count()

Double verification for null rows

shape: (1, 14)
┌─────┬────────────┬──────┬─────────────────────┬───┬─────┬─────┬─────┬─────┐
│ UDI ┆ Product ID ┆ Type ┆ Air temperature [K] ┆ … ┆ HDF ┆ PWF ┆ OSF ┆ RNF │
│ --- ┆ ---        ┆ ---  ┆ ---                 ┆   ┆ --- ┆ --- ┆ --- ┆ --- │
│ u32 ┆ u32        ┆ u32  ┆ u32                 ┆   ┆ u32 ┆ u32 ┆ u32 ┆ u32 │
╞═════╪════════════╪══════╪═════════════════════╪═══╪═════╪═════╪═════╪═════╡
│ 0   ┆ 0          ┆ 0    ┆ 0                   ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
└─────┴────────────┴──────┴─────────────────────┴───┴─────┴─────┴─────┴─────┘

In [135]:
print('Separating all column by type:\n')
identifier = [
    'UDI', 'Product ID', 'Type'
]
failure = [
    'TWF', 'HDF', 'PWF', 'OSF', 'RNF'
]
target = [
    'Machine failure'
]
operational = [
    'Air temperature [K]', 'Process temperature [K]', 'Rotational speed [rpm]',	'Torque [Nm]', 'Tool wear [min]'
]
print(f'Identifier: {identifier}')
print(f'Failure: {failure}')
print(f'Operational: {operational}')
print(f'Target: {target}')

Separating all column by type:

Identifier: ['UDI', 'Product ID', 'Type']
Failure: ['TWF', 'HDF', 'PWF', 'OSF', 'RNF']
Operational: ['Air temperature [K]', 'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]']
Target: ['Machine failure']

In [136]:
count = []
columns = []
for col in df_raw.columns:
    unique_values_failure = df_raw[col].unique().count()
    count.append(unique_values_failure)
    columns.append(col)

unique_values = pl.DataFrame({
    'columns' : columns,
    'count' : count
})
with pl.Config(tbl_rows= -1):
    display(unique_values)

shape: (14, 2)
┌─────────────────────────┬───────┐
│ columns                 ┆ count │
│ ---                     ┆ ---   │
│ str                     ┆ i64   │
╞═════════════════════════╪═══════╡
│ UDI                     ┆ 10000 │
│ Product ID              ┆ 10000 │
│ Type                    ┆ 3     │
│ Air temperature [K]     ┆ 93    │
│ Process temperature [K] ┆ 82    │
│ Rotational speed [rpm]  ┆ 941   │
│ Torque [Nm]             ┆ 577   │
│ Tool wear [min]         ┆ 246   │
│ Machine failure         ┆ 2     │
│ TWF                     ┆ 2     │
│ HDF                     ┆ 2     │
│ PWF                     ┆ 2     │
│ OSF                     ┆ 2     │
│ RNF                     ┆ 2     │
└─────────────────────────┴───────┘

In [137]:
df_by_type = df_raw.group_by('Type').agg(
    pl.len().alias('total_records'),
    pl.col(failure).sum()
    ).with_columns(
        (pl.col('total_records') / pl.col('total_records').sum()).alias('total_records_percentage')
    )
df_by_type

shape: (3, 8)
┌──────┬───────────────┬─────┬─────┬─────┬─────┬─────┬──────────────────────────┐
│ Type ┆ total_records ┆ TWF ┆ HDF ┆ PWF ┆ OSF ┆ RNF ┆ total_records_percentage │
│ ---  ┆ ---           ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ---                      │
│ str  ┆ u32           ┆ i64 ┆ i64 ┆ i64 ┆ i64 ┆ i64 ┆ f64                      │
╞══════╪═══════════════╪═════╪═════╪═════╪═════╪═════╪══════════════════════════╡
│ M    ┆ 2997          ┆ 14  ┆ 31  ┆ 31  ┆ 9   ┆ 2   ┆ 0.2997                   │
│ H    ┆ 1003          ┆ 7   ┆ 8   ┆ 5   ┆ 2   ┆ 4   ┆ 0.1003                   │
│ L    ┆ 6000          ┆ 25  ┆ 76  ┆ 59  ┆ 87  ┆ 13  ┆ 0.6                      │
└──────┴───────────────┴─────┴─────┴─────┴─────┴─────┴──────────────────────────┘

- Acording to documentation:
    - product ID: consisting of a letter L, M, or H for low (50% of all products), medium (30%) and high (20%) as product quality variants and a variant-specific serial number;
    - type: just the product type L, M or H from column 2.

In [138]:
df_raw = df_raw.with_columns(
    pl.when(pl.col('Type') == 'L').then(0)
    .when(pl.col('Type') == 'M').then(1)
    .otherwise(2).alias('Type')
)
print("'Type' column encoded")
df_raw.sample(10)

'Type' column encoded

shape: (10, 14)
┌──────┬────────────┬──────┬─────────────────────┬───┬─────┬─────┬─────┬─────┐
│ UDI  ┆ Product ID ┆ Type ┆ Air temperature [K] ┆ … ┆ HDF ┆ PWF ┆ OSF ┆ RNF │
│ ---  ┆ ---        ┆ ---  ┆ ---                 ┆   ┆ --- ┆ --- ┆ --- ┆ --- │
│ i64  ┆ str        ┆ i32  ┆ f64                 ┆   ┆ i64 ┆ i64 ┆ i64 ┆ i64 │
╞══════╪════════════╪══════╪═════════════════════╪═══╪═════╪═════╪═════╪═════╡
│ 2785 ┆ L49964     ┆ 0    ┆ 300.2               ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ 6134 ┆ L53313     ┆ 0    ┆ 301.1               ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ 2888 ┆ M17747     ┆ 1    ┆ 300.5               ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ 3723 ┆ L50902     ┆ 0    ┆ 302.2               ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ 5544 ┆ L52723     ┆ 0    ┆ 302.4               ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ 9883 ┆ L57062     ┆ 0    ┆ 298.8               ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ 1377 ┆ M16236     ┆ 1    ┆ 298.8               ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ 6846 ┆ M21705     ┆ 1    ┆ 301.3               ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ 1389 ┆ H30802     ┆ 2    ┆ 298.9               ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ 7264 ┆ L54443     ┆ 0    ┆ 300.4               ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
└──────┴────────────┴──────┴─────────────────────┴───┴─────┴─────┴─────┴─────┘

In [139]:
total_failures = df_raw.group_by('Machine failure').agg(
    pl.len().alias('total_records')
    ).with_columns(
        (pl.col('total_records') / pl.col('total_records').sum()).alias('percentage')
    )
print('Total failures:')
total_failures

Total failures:

shape: (2, 3)
┌─────────────────┬───────────────┬────────────┐
│ Machine failure ┆ total_records ┆ percentage │
│ ---             ┆ ---           ┆ ---        │
│ i64             ┆ u32           ┆ f64        │
╞═════════════════╪═══════════════╪════════════╡
│ 1               ┆ 339           ┆ 0.0339     │
│ 0               ┆ 9661          ┆ 0.9661     │
└─────────────────┴───────────────┴────────────┘

In [140]:
import plotly.express as px

fig = px.bar(
    data_frame= total_failures, x= 'Machine failure', y= 'total_records'
)

fig.show()

In [141]:
count = df_raw.select(pl.col(failure).sum()).row(0)
total = df_raw.filter(pl.col('Machine failure') == 1).group_by('Machine failure').agg(pl.len()).row(0)[1]

failure_distribution = pl.DataFrame({
    'failure' : failure,
    'count': count,
}).with_columns(
    (pl.col('count') / total * 100).alias('percentage_failures'),
        (pl.col('count') / df_raw.height *100).alias('percentage_total')
).sort('count', descending= False)
failure_distribution

shape: (5, 4)
┌─────────┬───────┬─────────────────────┬──────────────────┐
│ failure ┆ count ┆ percentage_failures ┆ percentage_total │
│ ---     ┆ ---   ┆ ---                 ┆ ---              │
│ str     ┆ i64   ┆ f64                 ┆ f64              │
╞═════════╪═══════╪═════════════════════╪══════════════════╡
│ RNF     ┆ 19    ┆ 5.60472             ┆ 0.19             │
│ TWF     ┆ 46    ┆ 13.569322           ┆ 0.46             │
│ PWF     ┆ 95    ┆ 28.023599           ┆ 0.95             │
│ OSF     ┆ 98    ┆ 28.908555           ┆ 0.98             │
│ HDF     ┆ 115   ┆ 33.923304           ┆ 1.15             │
└─────────┴───────┴─────────────────────┴──────────────────┘

In [142]:

fig = px.bar(failure_distribution, x= 'failure', y= 'count', title= 'Count of failure')
fig.show()

In [143]:
sum_machine_failure_errors = df_raw.filter(
    (pl.col(target) == 0) & (pl.sum_horizontal(failure) == 1)
).sum().select(
    pl.col(target),
    pl.col(failure)
).with_columns(
    pl.sum_horizontal(failure).alias('sum_failure')
)

sum_failure_errors = df_raw.filter(
    (pl.col(target) == 1) & (pl.sum_horizontal(failure) == 0)
).sum().select(
    pl.col(target),
    pl.col(failure)
).with_columns(
    pl.sum_horizontal(failure).alias('sum_failure')
)

print('Sum Machine Failures errors:')
print(sum_machine_failure_errors)
print('Sum Failure errors:')
print(sum_failure_errors)

for col in failure:
    anomalies = df_raw.filter((pl.col(col) == 1) & (pl.col(target) == 0))
    percentage = anomalies.shape[0] / df_raw.filter(pl.col(col) > 0 ).shape[0] *100
    if anomalies.shape[0] > 0:
        print(f'For {col}, total anomalies = {anomalies.shape[0]} with a percentage of {percentage}')

anomalies_mf = df_raw.filter((pl.col(target) == 1) & (pl.all_horizontal(pl.col(failure) == 0)))
percentage_mf = anomalies_mf.shape[0] / (df_raw.filter(pl.col(target) == 1)).shape[0] *100

print(f'For Machine Failure, total anomalies = {anomalies_mf.shape[0]} with a percentage of {percentage_mf}')

Sum Machine Failures errors:
shape: (1, 7)
┌─────────────────┬─────┬─────┬─────┬─────┬─────┬─────────────┐
│ Machine failure ┆ TWF ┆ HDF ┆ PWF ┆ OSF ┆ RNF ┆ sum_failure │
│ ---             ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ---         │
│ i64             ┆ i64 ┆ i64 ┆ i64 ┆ i64 ┆ i64 ┆ i64         │
╞═════════════════╪═════╪═════╪═════╪═════╪═════╪═════════════╡
│ 0               ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 18  ┆ 18          │
└─────────────────┴─────┴─────┴─────┴─────┴─────┴─────────────┘
Sum Failure errors:
shape: (1, 7)
┌─────────────────┬─────┬─────┬─────┬─────┬─────┬─────────────┐
│ Machine failure ┆ TWF ┆ HDF ┆ PWF ┆ OSF ┆ RNF ┆ sum_failure │
│ ---             ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ---         │
│ i64             ┆ i64 ┆ i64 ┆ i64 ┆ i64 ┆ i64 ┆ i64         │
╞═════════════════╪═════╪═════╪═════╪═════╪═════╪═════════════╡
│ 9               ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0           │
└─────────────────┴─────┴─────┴─────┴─────┴─────┴─────────────┘
For RNF, total anomalies = 18 with a percentage of 94.73684210526315
For Machine Failure, total anomalies = 9 with a percentage of 2.6548672566371683

- Since anomalies in RNF represent 94% of all failures in this column, it's worth excluding it
- Having 9 rows with "Machine failure" but no corresponding failure type tells us nothing, so it's worth excluding them

In [144]:
df = df_raw.filter(
    ((pl.col(target) == 0) & pl.all_horizontal(pl.col(failure) == 0))
    | ((pl.col(target) == 1) & pl.any_horizontal(pl.col(failure) == 1))
)
total_lines = df_raw.shape[0]
new_total_lines = df.shape[0]
sum_failures = df_raw.filter(
    ((pl.col(target) == 1) & pl.all_horizontal(pl.col(failure) == 0))
    | ((pl.col(target) == 0) & pl.any_horizontal(pl.col(failure) == 1))
).shape[0]

print(f'Rows removed: {total_lines - new_total_lines} (expected: {sum_failures})')

Rows removed: 27 (expected: 27)

In [145]:
try:
    df.write_csv('../data/processed/ai4i2020_new.csv')
    print('Dataset saved at /data/processed')
except:
    print('Fail to save')

Dataset saved at /data/processed